In [ ]:
import pandas as pd
import numpy as np
import os
import glob

#### Preprocess the final excel files

In [ ]:
csvs = [r"/content/drive/MyDrive/EarthEngine_Exports/Final_complete_NO_SM_dataset.csv"]

# Get all CSV files in the folder
df = pd.concat((pd.read_csv(file) for file in csvs), ignore_index=True)

##### First get rid of the Null values

In [ ]:
clean_df = df.dropna()

,Date,DOY_cos,DOY_sin,ET,Latitude,Longitude,NDVI,date,dgg_id,elevation,land_cover,precipitation,LST_Day_1km,Soil_Moisture_SMAP
1,2022-01-01,0.999852,0.017213,73.288649,37.849,23.832,5035.399668,2022-01-01,2084967,0.128792,20.0,0.0,14385.244651,0.201054
2,2022-01-01,0.999852,0.017213,72.288344,37.958,23.940,5624.397195,2022-01-01,2084968,0.107327,30.0,0.0,14346.885500,0.140282
4,2022-01-01,0.999852,0.017213,74.494446,37.963,23.761,3427.120247,2022-01-01,2084455,0.128792,50.0,0.0,14365.000000,0.110061
5,2022-01-01,0.999852,0.017213,74.067329,38.071,23.870,4997.359937,2022-01-01,2084456,0.000000,20.0,0.0,14316.894125,0.148318
6,2022-01-01,0.999852,0.017213,74.350030,37.966,23.583,4230.042109,2022-01-01,2083942,0.128792,80.0,0.0,14355.615547,0.143720

##### Second rescale and convert values

In [ ]:
clean_df.loc[:, 'NDVI'] = clean_df['NDVI'] * 0.0001
clean_df.loc[:, 'ET'] = clean_df['ET'] * 0.1
clean_df.loc[:, 'LST_Day_1km'] = clean_df['LST_Day_1km']  * 0.02 - 273.15
clean_df.loc[:, 'land_cover'] = clean_df['land_cover'].round(0)
clean_df.head(5)

,Date,DOY_cos,DOY_sin,ET,Latitude,Longitude,NDVI,date,dgg_id,elevation,land_cover,precipitation,LST_Day_1km,Soil_Moisture_SMAP
1,2022-01-01,0.999852,0.017213,7.328865,37.849,23.832,0.503540,2022-01-01,2084967,0.128792,20.0,0.0,14.554893,0.201054
2,2022-01-01,0.999852,0.017213,7.228834,37.958,23.940,0.562440,2022-01-01,2084968,0.107327,30.0,0.0,13.787710,0.140282
4,2022-01-01,0.999852,0.017213,7.449445,37.963,23.761,0.342712,2022-01-01,2084455,0.128792,50.0,0.0,14.150000,0.110061
5,2022-01-01,0.999852,0.017213,7.406733,38.071,23.870,0.499736,2022-01-01,2084456,0.000000,20.0,0.0,13.187882,0.148318
6,2022-01-01,0.999852,0.017213,7.435003,37.966,23.583,0.423004,2022-01-01,2083942,0.128792,80.0,0.0,13.962311,0.143720

##### One hot encoding for the land cover category

In [ ]:
landcover_map = {
10 : "Tree cover",
20 : "Shrubland",
30 : "Grassland",
40 : "Cropland",
50 : "Built-up",
60 : "Bare / sparse vegetation",
70 : "Snow and ice",
80 : "Permanent water bodies",
90 : "Herbaceous wetland",
95 : "Mangroves",
100 : "Moss and lichen"
}
clean_df.loc[:, 'LandCover_label'] = clean_df['land_cover'].map(landcover_map)

clean_df = pd.get_dummies(clean_df, columns=['LandCover_label'], prefix='', prefix_sep='')

In [ ]:
final_df = clean_df.drop(columns=['date', 'dgg_id', 'Date', 'land_cover'])
final_df.to_csv(r"/content/drive/MyDrive/EarthEngine_Exports\Final_Combined_Processed_NO_SM.csv")